name: webviewapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  #webview_flutter: ^4.8.0
  onesignal_flutter: ^5.2.5
  firebase_core: ^2.25.3
  flutter_easyloading: ^3.0.5
  connectivity_plus: ^6.0.5
  flutter_inappwebview: ^6.1.4
  cupertino_icons: ^1.0.6
  persistent_bottom_nav_bar: ^6.2.1
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4
  rename_app: ^1.6.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash_logo.jpg"
  min_sdk_android: 21

flutter_native_splash:
  color: "#3d94d8"
  image: "assets/splash_logo.jpg"
  android: true
  ios: true
  android_12:
    color: "#3d94d8"
    image: "assets/splash_logo.jpg"
    android: true
    ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/home/
    - assets/catalog/
    - assets/contact/
    - assets/profile/
    - assets/search/
    - assets/settings/
    - assets/shop/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
